language: go
go:
  - 1.6.3
  - 1.7.1
sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install opencl-headers nvidia-opencl-dev
install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
